### ISSUE TITLE
dataset read

### ISSUE THREAD

**Issue by gjfzjj1995** [ymcidence/TBH#6]
the file'dataset.py' in util.data, in the main function,  data = Dataset(set_name='cifar10', batch_size=256)     it = iter(data.test_data)     print(it)     x = next(it)     print(x) , it can error, the error is 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 103: invalid continuation byte', can you provide the origin file 'cifar10_fc7_train.mat' and 'cifar10_fc7_test.mat'

**Comment by ymcidence** [comment]
> the file'dataset.py' in util.data, in the main function, data = Dataset(set_name='cifar10', batch_size=256) it = iter(data.test_data) print(it) x = next(it) print(x) , it can error, the error is 'UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 103: invalid continuation byte', can you provide the origin file 'cifar10_fc7_train.mat' and 'cifar10_fc7_test.mat'

1. Please try to speak English or any other languages that you can correctly deliver next time.
2. Please check the README file, which already tells one to deal with the data, including how to use the example data maker and how to organize the data folders.
3. We have provided the download links of the corresponding tf.data.TFRecordDataset files so that one does not have to get a .mat file.
4. Please check your package version. Sometimes this can be the cause of many errors.

**Comment by gjfzjj1995** [comment]
Hello, thank you very much for the code you provided. I processed it according to your solution and found that the error is still reported. The reason for the error is the last step( next(it)), other aspects are normal
